development:
  adapter: mysql
  database: blessr_dev
  username: blessr
  password: pass

test:
  adapter: mysql
  database: blessr_test
  username: blessr
  password: pass

production:
  adapter: mysql
  database: blessr_prod
  username: blessr
  password: pass
